### ISSUE TITLE
isNaN 判断导致 line 无法转换

### ISSUE THREAD

**Issue by AngusFu** [pfan123/convertpath#1]
这里的会导致部分情况下 line 未被转换。

![image](https://user-images.githubusercontent.com/8180186/33180349-01965f22-d032-11e7-8728-691b93dc47a4.png)

```js
var x1 = '10', y1 = '11.1', x2 = '11.1', y2 = '10.1'
isNaN(x1 - y1 + x2 - y2)
```

![image](https://user-images.githubusercontent.com/8180186/33180480-7370d6ea-d032-11e7-96ad-6822504c3a56.png)

**Comment by pfan123** [comment]
不好意思，好久没关注这个仓库。这里是有点问题，我看了一下你提的pr改动比较多，防止影响过大，我先简单修复一下这个问题～
